export type Lang = "ar" | "en";
export type Bi = { ar: string; en: string };

export const b = (ar: string, en: string): Bi => ({ ar, en });

export const routes = [
  ["overview", b("نظرة عامة", "Framework overview")],
  ["domains", b("Learning Domains", "Learning Domains")],
  ["trifecta", b("Trifecta", "Trifecta")],
  ["comparison", b("مركز المقارنة", "Comparison centre")],
  ["cases", b("معمل الحالات", "Case diagnostic lab")],
  ["objective-builder", b("بناء الأهداف", "Objective builder")],
  ["station-builder", b("تصميم المحطة", "Station builder")],
  ["calibration", b("المعايرة", "Assessment calibration")],
  ["profile", b("ملف الأداء", "Performance profile")],
  ["aar", b("AAR والتدخل", "AAR & intervention")],
  ["checks", b("اختبارات المعرفة", "Knowledge checks")],
  ["references", b("المراجع", "Reference library")],
  ["about", b("عن المنهج", "About the framework")],
] as const;

export type Level = {
  name: Bi;
  definition: Bi;
  evidence: Bi;
  example: Bi;
  activity: Bi;
  assessment: Bi;
  mistake: Bi;
  objective: Bi;
};

export const cognitiveLevels: Level[] = [
  {
    name: b("1. يتذكر — Remember", "1. Remember"),
    definition: b("يسترجع قاعدة أو خطوة أو معيارًا دون تفسيره.", "Recalls a rule, step, or standard without yet explaining it."),
    evidence: b("يسمي القاعدة أو يرتب الخطوات بدقة.", "Names the rule or sequences the steps accurately."),
    example: b("يذكر شروط الأمان الأربعة قبل المحطة.", "States the four safety conditions before the station."),
    activity: b("بطاقات استرجاع + Brief قصير.", "Retrieval cards and a short brief."),
    assessment: b("سؤال مباشر أو ترتيب بطاقات.", "Direct question or sequence task."),
    mistake: b("اعتبار التذكر دليلًا على التطبيق تحت الضغط.", "Treating recall as proof of application under pressure."),
    objective: b("قبل المحطة، يسرد المتدرب شروط الأمان الأربعة دون مساعدة وبترتيب صحيح.", "Before the station, the learner will state all four safety conditions unaided and in the correct order."),
  },
  {
    name: b("2. يفهم — Understand", "2. Understand"),
    definition: b("يشرح المعنى والسبب والعلاقة بين القاعدة والنتيجة.", "Explains meaning, rationale, and the link between a rule and its consequence."),
    evidence: b("يشرح بلغته ويعطي مثالًا وغير مثال.", "Explains in their own words and gives an example and non-example."),
    example: b("يشرح لماذا السرعة لا تعوّض Critical Safety Failure.", "Explains why speed cannot compensate for a Critical Safety Failure."),
    activity: b("شرح نظير + مقارنة حالتين.", "Peer explanation and case comparison."),
    assessment: b("سؤال لماذا/كيف مع مثال تطبيقي.", "Why/how question with an applied example."),
    mistake: b("استخدام كلمة «يفهم» في الهدف دون دليل ملاحظ.", "Using “understand” in an objective without observable evidence."),
    objective: b("بعد مقارنة حالتين، يشرح المتدرب سبب قرار No-Go مستشهدًا بدليلين ملاحظين.", "After comparing two cases, the learner will explain the No-Go decision using two observable facts."),
  },
  {
    name: b("3. يطبق — Apply", "3. Apply"),
    definition: b("يستخدم القاعدة أو الإجراء في موقف محدد.", "Uses the rule or procedure in a defined situation."),
    evidence: b("ينفذ السلوك المطلوب وفق الشرط والمعيار.", "Performs the required behaviour under the stated condition and standard."),
    example: b("يطبق قرار الإيقاف فور ظهور علامة أمان محددة.", "Applies the stop decision when a defined safety cue appears."),
    activity: b("تدريب موجه ثم محاولة مستقلة.", "Guided practice followed by an independent attempt."),
    assessment: b("Checklist سلوكي داخل محطة.", "Behavioural checklist in a station."),
    mistake: b("تقييم التطبيق بسؤال نظري فقط.", "Assessing application with a knowledge question only."),
    objective: b("أثناء ثلاث محاولات، يطبق قرار الإيقاف عند الإشارة المحددة خلال ثانيتين دون Critical Failure.", "Across three trials, the learner will apply the stop decision within two seconds of the defined cue with no Critical Failure."),
  },
  {
    name: b("4. يحلل — Analyze", "4. Analyze"),
    definition: b("يفكك الأداء ويحدد أول نقطة انهيار والعلاقات بين الأسباب.", "Breaks performance down and identifies the first point of failure and causal links."),
    evidence: b("يفصل الحقيقة عن الافتراض ويرتب الأسباب المحتملة.", "Separates facts from assumptions and orders plausible causes."),
    example: b("يميز بين نسيان التعليمات وعدم ثبات المهارة بعد دخول Timer.", "Distinguishes lost instruction recall from unstable skill after a timer is introduced."),
    activity: b("فيديو قصير + Evidence Matrix.", "Short observation clip and evidence matrix."),
    assessment: b("تحليل حالة مع بديل تفسيري.", "Case analysis with an alternative explanation."),
    mistake: b("القفز من النتيجة إلى تشخيص واحد.", "Jumping from an outcome to a single diagnosis."),
    objective: b("بعد حالة مسجلة، يحدد المتدرب أول نقطة انهيار وسببين محتملين وما يلزم لاختبار كل سبب.", "After a recorded case, the learner will identify the first breakdown point, two plausible causes, and evidence needed to test each."),
  },
  {
    name: b("5. يقيّم — Evaluate", "5. Evaluate"),
    definition: b("يحكم على الأداء باستخدام معيار معلن ودليل كافٍ.", "Judges performance against an explicit standard using sufficient evidence."),
    evidence: b("يصدر Go / No-Go / Need More Data ويبرر القرار.", "Issues Go / No-Go / Need More Data and justifies it."),
    example: b("يرفض درجة مرتفعة عند وجود Critical Safety Failure.", "Rejects a high total score when a Critical Safety Failure occurred."),
    activity: b("معايرة مقيمين على نفس الحالة.", "Assessor calibration on the same case."),
    assessment: b("قرار موثق + مستوى ثقة + بيانات ناقصة.", "Documented decision, confidence level, and missing data."),
    mistake: b("تحويل التفضيل الشخصي إلى معيار.", "Turning instructor preference into a standard."),
    objective: b("باستخدام Checklist معتمد، يصدر المقيم قرارًا متسقًا ويستشهد بكل بند حاسم.", "Using the approved checklist, the assessor will issue a consistent decision and cite every decisive item."),
  },
  {
    name: b("6. يبتكر / يحسّن — Create / Improve", "6. Create / Improve"),
    definition: b("يعيد تصميم درس أو محطة استنادًا إلى الدليل.", "Redesigns a lesson or station from evidence."),
    evidence: b("ينتج تعديلًا قابلًا للاختبار مع سبب ومعيار إعادة تقييم.", "Produces a testable change with a rationale and retest criterion."),
    example: b("يفصل متغيرات محطة كشفت انهيارًا جماعيًا غير قابل للتفسير.", "Separates station variables after an uninterpretable group-wide collapse."),
    activity: b("ورشة إعادة تصميم + مراجعة زميل.", "Redesign workshop and peer review."),
    assessment: b("Station Card محسنة مع مقارنة قبل/بعد.", "Improved Station Card with before/after comparison."),
    mistake: b("إضافة تعقيد جديد دون Baseline أو بيانات.", "Adding complexity without a baseline or data."),
    objective: b("بعد تحليل بيانات ثلاث مجموعات، يعيد المدرب تصميم محطة تقلل المتغيرات المتزامنة وتحدد Retest Rule.", "After reviewing three group datasets, the trainer will redesign the station to reduce simultaneous variables and define a retest rule."),
  },
];

const level = (
  name: Bi, definition: Bi, evidence: Bi, example: Bi, activity: Bi,
  assessment: Bi, mistake: Bi, objective: Bi,
): Level => ({ name, definition, evidence, example, activity, assessment, mistake, objective });

export const psychomotorLevels: Level[] = [
  level(b("1. التقليد — Imitation","1. Imitation"),b("يشاهد نموذجًا ويحاكيه.","Observes a model and copies it."),b("يكرر الشكل العام مع دعم كثيف.","Repeats the overall pattern with substantial support."),b("يحاكي تسلسلًا آمنًا ببطء.","Copies a safe sequence slowly."),b("عرض واضح ثم أجزاء قصيرة.","Clear demonstration followed by short segments."),b("ملاحظة مباشرة دون حكم ثبات.","Direct observation without claiming stability."),b("اعتبار المحاكاة إتقانًا.","Treating imitation as mastery."),b("بعد العرض، يحاكي المتدرب التسلسل الآمن مرة واحدة مع توجيه كامل.","After the demonstration, the learner will copy the safe sequence once with full guidance.")),
  level(b("2. التنفيذ الموجه — Guided execution","2. Guided execution"),b("ينفذ بعد Brief أو Cue.","Performs after a brief or cue."),b("يحتاج تذكيرًا أو تصحيحًا أثناء الأداء.","Requires prompts or correction during performance."),b("يكمل الإجراء مع تلميحين كحد أقصى.","Completes the procedure with no more than two prompts."),b("تدريب موجه وتغذية راجعة فورية.","Guided practice with immediate feedback."),b("Checklist يسجل مقدار الدعم.","Checklist records the amount of support."),b("إخفاء مقدار مساعدة المدرب.","Failing to record instructor assistance."),b("ينفذ المتدرب التسلسل مع تلميحين كحد أقصى ودون Critical Failure.","The learner will perform the sequence with no more than two prompts and no Critical Failure.")),
  level(b("3. الدقة — Precision","3. Precision"),b("ينفذ بدقة ودعم محدود.","Performs accurately with limited support."),b("نتيجة صحيحة مع تباين بسيط.","Correct output with only minor variation."),b("يحقق المعيار في ثلاث محاولات متتالية.","Meets the standard in three consecutive trials."),b("تكرار متعمد حول خطأ واحد.","Deliberate repetition focused on one error."),b("نسبة نجاح واتساق عبر المحاولات.","Pass rate and consistency across trials."),b("اعتبار محاولة ناجحة واحدة دليلًا كافيًا.","Treating one successful attempt as sufficient evidence."),b("يحقق المتدرب بنود الدقة في 3 من 3 محاولات مستقلة.","The learner will meet all precision items in 3 of 3 independent trials.")),
  level(b("4. التنسيق — Coordination / articulation","4. Coordination / articulation"),b("يربط خطوات متعددة دون فقد السيطرة.","Links multiple steps without losing control."),b("انتقالات منظمة وتسلسل كامل.","Organized transitions and a complete sequence."),b("يربط قرارًا بتسلسل فني آمن.","Links a decision to a safe technical sequence."),b("تدريب أجزاء ثم ربطها تدريجيًا.","Part practice followed by progressive integration."),b("Checklist تسلسلي تحت متغير واحد.","Sequential checklist under one added variable."),b("إضافة الوقت والحمل والتعليمات معًا.","Adding time, load, and instructions together."),b("يربط المتدرب أربع خطوات بالترتيب تحت متغير واحد دون فقد بند حاسم.","The learner will link four steps in order under one added variable without losing a critical item.")),
  level(b("5. الثبات والتلقائية — Stable / naturalized","5. Stable / naturalized"),b("يحافظ على الأداء مستقلًا وبصورة متكررة.","Maintains independent, repeatable performance."),b("اتساق عبر محاولات وأيام وشروط مصرح بها.","Consistency across trials, days, and authorized conditions."),b("يحافظ على السلوك الآمن مع ضغط تدريجي.","Maintains safe behaviour as pressure is progressed."),b("تكرار موزع مع Authorized Variation.","Distributed practice with authorized variation."),b("اختبارات متكررة وRetest.","Repeated assessments and retest."),b("افتراض الثبات من جلسة واحدة.","Assuming stability from one session."),b("يحافظ المتدرب على المعيار في 90% من المحاولات عبر جلستين ودون Critical Failure.","The learner will retain the standard in 90% of trials across two sessions with no Critical Failure.")),
];

export const affectiveLevels: Level[] = [
  level(b("1. الانتباه — Receiving","1. Receiving / attending"),b("ينتبه للـBrief ولإشارات السلامة.","Attends to the brief and safety cues."),b("يوقف المشتت ويعيد النقطة الحاسمة.","Stops the distraction and repeats the critical point."),b("يستمع ويؤكد فهم قرار الإيقاف.","Listens and confirms the stop decision."),b("Brief قصير مع تحقق استرجاع.","Short brief with a recall check."),b("ملاحظة سلوكية أثناء الـBrief.","Behavioural observation during the brief."),b("اعتبار الانتباه دليل التزام ثابت.","Treating attention as proof of consistent commitment."),b("أثناء الـBrief، يعيد المتدرب نقطة الأمان الحاسمة دون تذكير.","During the brief, the learner will repeat the critical safety point without prompting.")),
  level(b("2. المشاركة — Responding","2. Responding"),b("يستجيب ويقبل التصحيح.","Responds and accepts correction."),b("ينفذ التصحيح دون إخفاء الخطأ.","Applies correction without concealing the error."),b("يبلغ عن خطئه ويعيد المحاولة وفق التوجيه.","Reports the error and retries under guidance."),b("تصحيح واحد ثم إعادة محاولة.","One correction followed by a retry."),b("Checklist للاستجابة للتصحيح.","Checklist for response to correction."),b("تقييم النبرة بدل السلوك.","Judging tone instead of behaviour."),b("بعد التصحيح، يعيد المتدرب المحاولة وفق التوجيه دون تذكير إضافي.","After correction, the learner will retry as directed without an additional prompt.")),
  level(b("3. التقدير — Valuing","3. Valuing"),b("يعطي الأمان والانضباط أولوية ظاهرة.","Gives safety and discipline observable priority."),b("يختار السلوك الآمن ولو خسر وقتًا.","Chooses safe behaviour even when it costs time."),b("لا يختصر قاعدة أمان لتحسين النتيجة.","Does not shortcut a safety rule to improve the result."),b("سيناريو مفاضلة مضبوط.","Controlled trade-off scenario."),b("ملاحظة القرار في أكثر من محاولة.","Observe the decision across multiple trials."),b("استنتاج قيمة داخلية من قول المتدرب.","Inferring internal values from what the learner says."),b("عبر ثلاث محاولات، يختار المتدرب السلوك الآمن قبل السرعة دون تذكير.","Across three trials, the learner will prioritize safe behaviour over speed without prompting.")),
  level(b("4. تنظيم السلوك — Organizing","4. Organizing behaviour"),b("يرتب قراراته بحيث تحكم القيم الأداء.","Organizes decisions so values govern performance."),b("يستخدم روتينًا ثابتًا يسبق السرعة.","Uses a consistent routine before pursuing speed."),b("يوقف نفسه ويعيد الضبط عند الشك.","Self-stops and resets when uncertain."),b("محاولات متعددة مع تغير بسيط.","Multiple trials with minor variation."),b("نمط سلوكي عبر شروط مصرح بها.","Behaviour pattern across authorized conditions."),b("اعتبار الامتثال في الهدوء كافيًا.","Treating quiet-condition compliance as sufficient."),b("عند الشك، يطبق المتدرب قرار الإيقاف والـReset في 3 من 3 محاولات.","When uncertain, the learner will apply the stop and reset decision in 3 of 3 trials.")),
  level(b("5. الالتزام الداخلي — Internalizing","5. Internalizing / consistent compliance"),b("يلتزم باستمرار دون رقابة مباشرة.","Complies consistently without direct supervision."),b("سلوك ثابت عبر الوقت والضغط والتصحيح.","Stable behaviour across time, pressure, and correction."),b("يحافظ على الأمان بعد خطأ أو Timer.","Maintains safety after an error or timer."),b("ملاحظة طولية في شروط مصرح بها.","Longitudinal observation under authorized conditions."),b("دليل متكرر عبر جلسات ومقيمين.","Repeated evidence across sessions and assessors."),b("وصف شخصية أو تشخيص نفسي.","Using personality labels or psychological diagnosis."),b("يحافظ المتدرب على السلوك الحاسم عبر جلستين وجميع المحاولات دون تذكير.","The learner will maintain the critical behaviour across two sessions and all trials without prompting.")),
];

export type CognitiveFamily = {
  code: string; name: string; phase: Bi; definition: Bi; question: Bi; evidence: Bi;
  metric: Bi; misdiagnosis: Bi; alternative: Bi; method: Bi; limit: Bi;
};

export const cognitiveFamilies: CognitiveFamily[] = [
  ["SA","Situational Awareness", "الإدراك والتحكم الذهني","Perception and mental control","يرصد المعلومة المهمة ويفهم معناها ويتابع تغيرها.","Detects relevant information, understands its meaning, and tracks change.","شاف إيه؟ وفهم منه إيه؟","What did the performer see and understand?","Cue فائت، تغطية بصرية ضيقة، أو تفسير خاطئ لمؤشر لوحظ.","Missed cue, narrowed scan, or incorrect interpretation of a detected cue.","زمن اكتشاف الإشارة + دقة تفسيرها.","Cue detection time plus interpretation accuracy.","أي خطأ قرار = ضعف SA.","Any wrong decision means poor SA.","الإشارة غير واضحة أو الـBrief ملتبس.","The cue was unclear or the brief was ambiguous.","Cue-detection practice بمتغير واحد.","Single-variable cue-detection practice.","لا نستنتج SA من النتيجة النهائية وحدها.","Do not infer SA from the final outcome alone."],
  ["CLM","Cognitive Load Management","الإدراك والتحكم الذهني","Perception and mental control","يعالج المعلومات دون تشبع يكسر الأداء.","Processes information without saturation that disrupts performance.","عند أي حمل بدأ الأداء يتكسر؟","At what load did performance begin to break?","إسقاط بند ثابت بعد إضافة معلومات أو مهام.","A stable item drops after information or tasks are added.","معدل الخطأ عند كل مستوى حمل.","Error rate at each load level.","كل نسيان = ضعف ذاكرة.","Every omission is weak memory.","تعدد متغيرات المحطة أو Brief زائد.","Too many station variables or an overloaded brief.","Baseline ثم إضافة عامل واحد في كل مرة.","Baseline, then add one factor at a time.","الحمل يعتمد على الخبرة وتصميم المهمة؛ ليس صفة ثابتة.","Load depends on expertise and task design; it is not a fixed trait."],
  ["DMUS","Decision-Making Under Stress","اتخاذ القرار والتنفيذ","Decision and execution","يختار قرارًا صحيحًا في وقت مناسب وملتزمًا بالقواعد.","Selects a correct, timely, rule-compliant decision.","هل القرار صحيح تحت الضغط؟","Was the selected decision correct under pressure?","قرار خاطئ، Freeze، تردد زائد، أو اندفاع قبل الفهم.","Wrong decision, freeze, excessive hesitation, or action before comprehension.","دقة القرار + زمنه + الالتزام.","Decision accuracy, latency, and compliance.","الأسرع هو الأفضل.","Faster is always better.","المعيار أو الإشارة غير واضحين.","The criterion or cue was unclear.","قرار تدريجي تحت وقت مضبوط مع Reset.","Progressive decision practice under controlled time with reset.","الزمن وحده لا يصف جودة القرار.","Latency alone does not describe decision quality."],
  ["WMTR","Working Memory & Tactical Recall","اتخاذ القرار والتنفيذ","Decision and execution","يحتفظ بالتعليمات المطلوبة أثناء الأداء ويسترجعها عند الحاجة.","Retains required instructions during performance and recalls them when needed.","هل فضلت المعلومة موجودة وقت احتياجها؟","Did the performer retain the instruction when it was needed?","يعيد الشروط قبل البداية ثم يسقط أحدها أثناء التنفيذ.","Repeats conditions before start but drops one during execution.","دقة استرجاع البند الحاسم في توقيته.","Timely recall accuracy for mission-critical items.","عدم الامتثال = موقف سلوكي.","Non-compliance proves an attitude problem.","Brief طويل أو Cue متأخر.","An overlong brief or late cue.","تقليل عناصر الذاكرة ثم زيادتها تدريجيًا.","Reduce memory items, then increase progressively.","يجب مقارنة قبل/أثناء/بعد لتجنب التخمين.","Compare before, during, and after to avoid guessing."],
  ["CFA","Cognitive Flexibility & Adaptability","اتخاذ القرار والتنفيذ","Decision and execution","يغيّر الخطة عندما تتغير المعلومة بدل تكرار القاعدة القديمة.","Changes the plan when information changes instead of repeating the old rule.","هل غيّر الخطة لما الشرط اتغير؟","Could the performer change the plan when the condition changed?","يلاحظ التحديث لكنه يعود للنمط السابق.","Detects the update but reverts to the previous pattern.","زمن إعادة التخطيط + عدد التذكيرات.","Replanning time plus prompts required.","الخطأ دائمًا عدم فهم.","The error always means lack of understanding.","التحديث غير مميز أو جاء متأخرًا.","The update was not salient or arrived late.","تغيير واحد واضح مع وقت كافٍ ثم تقليل الدعم.","One clear change with adequate time, then reduce support.","افصل ملاحظة التغيير عن تنفيذ التكيف.","Separate detecting change from executing adaptation."],
  ["ERSI","Emotional Resilience & Stress Inoculation","التزامن النفسي والبدني","Psychophysical coordination","يستعيد التنظيم بعد خطأ أو ضغط دون سلسلة أخطاء.","Regains organization after error or pressure without a cascading failure.","بعد الخطأ… عرف يرجع؟","After the error, could the performer recover?","الخطأ الأول يولد اندفاعًا أو تجمدًا أو فقد استقبال التصحيح.","The first error triggers rushing, freeze, or failure to receive correction.","زمن العودة للـBaseline + جودة المحاولة التالية.","Time to baseline plus quality of the next attempt.","ارتفاع النبض يثبت ضعف المرونة.","Heart rate proves poor resilience.","تعب بدني أو معيار غير واقعي.","Physical fatigue or an unrealistic criterion.","Reset واضح، ضغط تدريجي، وAAR غير عقابي.","Defined reset, progressive pressure, and non-punitive AAR.","مؤشر فسيولوجي واحد لا يثبت حالة انفعالية.","One physiological indicator does not prove an emotional state."],
  ["MCC","Motor-Cognitive Coupling","التزامن النفسي والبدني","Psychophysical coordination","يحوّل القرار الصحيح إلى الفعل الجسدي المطابق.","Turns the correct decision into the corresponding physical action.","هل القرار الصح بقى فعلًا صح؟","Did the correct decision become the correct physical action?","الإجابة اللفظية صحيحة لكن الحركة لا تطابقها.","Verbal answer is correct but the movement does not match it.","نسبة تطابق القرار المعلن والفعل.","Decision-to-action match rate.","كل فعل خاطئ قرار خاطئ.","Every wrong action was a wrong decision.","المهارة نفسها غير ثابتة.","The skill itself is unstable.","قرار-فعل بطيء ثم سرعة تدريجية.","Slow decision-action pairing, then progressive speed.","يلزم إثبات صحة القرار قبل وصف فجوة الربط.","Confirm the decision was correct before labeling a coupling gap."],
  ["RSVMI","Reaction Speed & Visual-Motor Integration","التزامن النفسي والبدني","Psychophysical coordination","يستجيب بصريًا بسرعة مع دقة وتوافق حركي.","Responds to visual information with speed, accuracy, and motor coordination.","رد فعله سريع ودقيق معًا؟","Was the response both fast and accurate?","زمن جيد مع اختيارات خاطئة أو حركة غير متوافقة.","Fast time with wrong selection or poorly coordinated action.","زمن الاستجابة + دقة الاختيار + اتساق الحركة.","Response time, choice accuracy, and movement consistency.","زمن رد الفعل وحده يثبت التكامل.","Reaction time alone proves integration.","توقع الإشارة أو اختلاف وضوحها.","Cue anticipation or unequal cue visibility.","إشارات متوازنة، محاولات متعددة، ودقة قبل السرعة.","Balanced cues, repeated trials, and accuracy before speed.","لا تساوي بين السرعة المفردة والقدرة المتكاملة.","Do not equate one fast time with integrated capability."],
  ["FRFRC","Fatigue-Resistant Focus & Reset Cycles","الحفاظ على الأداء","Sustained performance","يحافظ على التركيز ويستعيده عبر أداء ممتد وتكرار.","Maintains and restores focus across sustained, repeated performance.","هل كمل بنفس الجودة وعرف يعمل Reset؟","Could performance remain stable and reset when needed?","زيادة تشتت أو أخطاء متتابعة مع الوقت ثم تحسن بعد Reset.","Rising distraction or repeated errors over time followed by improvement after reset.","اتجاه الخطأ عبر الزمن + جودة ما بعد Reset.","Error trend over time plus post-reset quality.","كل تدهور ذهني.","Every decline is cognitive.","حمل بدني أو صعوبة فنية متزايدة.","Physical load or increasing technical difficulty.","فترات عمل مضبوطة وReset محدد ثم زيادة تدريجية.","Controlled work periods with defined resets, then progression.","افصل أثر الوقت عن التعب البدني وتصميم المحطة.","Separate time-on-task from physical fatigue and station design."],
  ["SCR","Sleep & Circadian Resilience","الحفاظ على الأداء","Sustained performance","يحافظ نسبيًا على الأداء مع تغير النوم والتوقيت اعتمادًا على بيانات طولية.","Maintains performance across sleep and timing variation using longitudinal evidence.","هل التوقيت والنوم يفسران نمطًا متكررًا؟","Do sleep and timing explain a repeated pattern?","تدهور متكرر مرتبط بسجل نوم وتوقيت عبر عدة أيام.","Repeated decline associated with sleep and timing records over several days.","سجل نوم/توقيت + اتجاه أداء طولي.","Sleep/timing log plus longitudinal performance trend.","أداء سيئ صباحًا يثبت مشكلة نوم.","One poor morning proves a sleep issue.","مرض، عبء عمل، أو تغيير في المهمة.","Illness, workload, or task change.","إدارة الجدول والنوم؛ لا تستخدم حرمانًا متعمدًا في التدريب.","Schedule and sleep management; do not use deliberate deprivation as training.","يتطلب بيانات طولية ولا يُشخّص من جلسة واحدة.","Requires longitudinal data and cannot be inferred from one session."],
].map(([code,name,pa,pe,da,de,qa,qe,ea,ee,ma,me,mia,mie,aa,ae,mta,mte,la,le]) => ({
  code,name,phase:b(pa,pe),definition:b(da,de),question:b(qa,qe),evidence:b(ea,ee),metric:b(ma,me),
  misdiagnosis:b(mia,mie),alternative:b(aa,ae),method:b(mta,mte),limit:b(la,le)
}));

export type Case = {
  id: number; level: "basic" | "intermediate" | "advanced"; title: Bi; scenario: Bi;
  facts: Bi[]; assumptions: Bi[]; domain: string; pillar: string; primary: Bi; secondary: Bi;
  missing: Bi; intervention: Bi; decision: "Go" | "No-Go" | "Need More Data";
};

const C = (id:number, level:Case["level"], ar:string,en:string, sar:string,sen:string, facts:string[], factsEn:string[], assumptions:string[], assumptionsEn:string[], domain:string,pillar:string,primary:Bi,secondary:Bi,missing:Bi,intervention:Bi,decision:Case["decision"]):Case => ({
  id,level,title:b(ar,en),scenario:b(sar,sen),facts:facts.map((x,i)=>b(x,factsEn[i])),assumptions:assumptions.map((x,i)=>b(x,assumptionsEn[i])),domain,pillar,primary,secondary,missing,intervention,decision
});

export const cases: Case[] = [
  C(1,"basic","دقة مع خرق أمان","Accuracy with a safety violation","حقق المتدرب النتيجة المطلوبة، لكنه تجاوز قرار إيقاف معلنًا مرة واحدة.","The learner met the accuracy standard but ignored a defined stop cue once.",["حقق معيار الدقة","تجاوز قرار الإيقاف"],["Accuracy standard met","Stop cue ignored"],["كان مستهترًا"],["The learner was careless"],"Affective","Technical",b("سلوك الأمان فشل","Safety behaviour failed"),b("الامتثال الفني فشل","Technical compliance failed"),b("هل رأى الإشارة وفهمها؟","Did the learner detect and understand the cue?"),b("إيقاف المحطة، تثبيت Baseline، وإعادة تقييم الإشارة والسلوك.","Stop the station, restore baseline, and reassess cue detection and behaviour."),"No-Go"),
  C(2,"basic","محاولة واحدة ناجحة","One successful attempt","نجحت المحاولة الأولى بعد عرض المدرب، ولا توجد محاولات أخرى.","The first attempt succeeded after the instructor demonstration; no other trials exist.",["محاولة واحدة صحيحة","سبقها عرض مباشر"],["One correct attempt","Immediately followed a demonstration"],["المهارة ثابتة"],["The skill is stable"],"Psychomotor","Technical",b("الثبات غير مثبت","Stability is not demonstrated"),b("احتمال أثر التقليد","Possible imitation effect"),b("اتساق عبر محاولات وجلسات.","Consistency across trials and sessions."),b("تكرار موزع مع تقليل الدعم وتسجيل الاتساق.","Distributed repetition with reduced support and recorded consistency."),"Need More Data"),
  C(3,"basic","يعرف ولا يطبق","Knows but does not apply","شرح القاعدة بدقة، ثم لم يطبقها في محاولة بطيئة غير مضغوطة.","The learner explained the rule accurately, then failed to apply it in a slow, unpressured trial.",["شرح صحيح","عدم تطبيق دون ضغط"],["Correct explanation","No application under low pressure"],["لا يهتم"],["Does not care"],"Cognitive","Technical",b("فجوة تطبيق","Application gap"),b("قد تكون المهارة غير متكونة","Skill may not yet be developed"),b("هل يستطيع التنفيذ بتوجيه؟","Can the learner perform with guidance?"),b("Demonstration ثم Guided Practice وChecklist.","Demonstration, guided practice, and checklist."),"No-Go"),
  C(4,"basic","تصحيح مقبول ثم خطأ متكرر","Correction accepted, error repeated","أقرّ المتدرب بالتصحيح، لكنه كرر نفس الخطأ الفني في محاولتين تاليتين.","The learner accepted correction but repeated the same technical error in two later trials.",["قبل التصحيح لفظيًا","تكرر الخطأ مرتين"],["Verbally accepted correction","Error repeated twice"],["يرفض التعلم"],["Refuses to learn"],"Psychomotor","Technical",b("التنفيذ الموجه غير كافٍ","Guided execution is insufficient"),b("قد يكون Cue التصحيح غير واضح","Correction cue may be unclear"),b("نوع الدعم والزمن بين المحاولات.","Support used and time between attempts."),b("تجزئة الحركة، Cue واحد، وتغذية راجعة فورية.","Break the movement down, use one cue, and give immediate feedback."),"No-Go"),
  C(5,"basic","نسي شرطًا","Forgotten condition","أعاد ثلاثة شروط قبل البداية، ثم نسي الشرط الثاني أثناء الأداء وتذكره بعد النهاية.","The learner repeated three conditions before start, forgot the second during performance, and recalled it afterward.",["تذكر قبل","نسي أثناء","تذكر بعد"],["Recalled before","Forgot during","Recalled after"],["ذاكرته ضعيفة دائمًا"],["Always has poor memory"],"Cognitive","Cognitive",b("WMTR محتمل","WMTR is plausible"),b("CLM محتمل","CLM is plausible"),b("هل يتكرر مع عنصرين فقط؟","Does it recur with only two items?"),b("تقليل عناصر الـBrief ثم الزيادة تدريجيًا.","Reduce brief items, then add them progressively."),"Need More Data"),
  C(6,"intermediate","ينهار مع Timer","Collapses with a timer","الأداء آمن وثابت ببطء. بعد إضافة Timer نسي شرطًا، استعجل، وفشل في الأمان.","Performance is safe and stable at baseline. With a timer, one condition is forgotten, rushing appears, and safety fails.",["Baseline ناجح","Timer هو المتغير الجديد","Critical Safety Failure"],["Baseline passed","Timer was the new variable","Critical Safety Failure"],["ضعيف تحت الضغط"],["Weak under pressure"],"Psychomotor","Cognitive",b("CLM / WMTR محتمل","CLM / WMTR plausible"),b("الثبات الحركي تحت التعقيد غير مثبت","Motor stability under complexity is unproven"),b("أول بند انهار عند مستويات وقت مختلفة.","First breakdown point at graded time levels."),b("عودة للـBaseline، وقت تدريجي، عامل واحد، Reset، ثم Retest.","Return to baseline, progressive time, one factor, reset, and retest."),"No-Go"),
  C(7,"intermediate","تدهور عبر التكرار","Decline across repetitions","المحاولتان الأوليان ناجحتان، ثم ينخفض الاتساق وتطول الاستعادة عبر ست محاولات.","The first two trials pass; consistency then declines and recovery slows across six trials.",["انخفاض تدريجي","استعادة أبطأ"],["Progressive decline","Slower recovery"],["لياقته ضعيفة"],["Poor general fitness"],"Psychomotor","Physical",b("قدرة الجسم على دعم المهمة موضع سؤال","Body support for the task is in question"),b("FRFRC أو جرعة المحطة محتملان","FRFRC or station dose may contribute"),b("الحمل، الراحة، والـBaseline بعد Reset.","Load, rest, and post-reset baseline."),b("تقليل الجرعة، تحديد Reset، ثم Load Progression.","Reduce dose, define reset, then progress load."),"Need More Data"),
  C(8,"intermediate","الشرط تغيّر","Condition changed","سمع المتدرب تحديثًا واضحًا وكرره، لكنه بدأ الجولة التالية بالخطة القديمة.","The learner heard and repeated a clear update but began the next trial using the old plan.",["كرر التحديث","نفذ الخطة القديمة"],["Repeated update","Used old plan"],["عنيد"],["Stubborn"],"Cognitive","Cognitive",b("CFA محتمل","CFA is plausible"),b("MCC محتمل إذا كان القرار اللفظي صحيحًا لحظة التنفيذ","MCC plausible if the live decision was correct"),b("قرار لفظي فور Cue + فيديو التوقيت.","Live verbal decision at cue plus timing observation."),b("تدريب تغيير واحد بمهلة واضحة ثم تقليلها.","Practice one clear change with adequate time, then reduce it."),"Need More Data"),
  C(9,"intermediate","قرار صحيح، فعل خاطئ","Correct decision, wrong action","أعلن المتدرب الاختيار الصحيح ثم نفذ فعلًا لا يطابقه في محاولتين.","The learner stated the correct choice, then performed a non-matching action in two trials.",["القرار المعلن صحيح","الفعل لم يطابقه مرتين"],["Stated decision correct","Action mismatched twice"],["لا يركز"],["Not focused"],"Psychomotor","Cognitive",b("MCC محتمل","MCC is plausible"),b("عدم ثبات المهارة الفنية","Technical skill instability"),b("اختبار الفعل نفسه دون قرار متغير.","Test the action without changing decisions."),b("ربط قرار-فعل ببطء، ثم زيادة السرعة بعد الاتساق.","Pair decision and action slowly, then add speed after consistency."),"No-Go"),
  C(10,"intermediate","خلاف بين المقيمين","Assessor disagreement","المقيم الأول سجل Go والثاني No-Go لنفس الأداء؛ بند «سيطرة جيدة» بلا مرساة سلوكية.","One assessor recorded Go and another No-Go; the item “good control” has no behavioural anchor.",["قراران مختلفان","البند غامض"],["Different decisions","Item is ambiguous"],["أحدهما غير كفء"],["One assessor is incompetent"],"Cognitive","Technical",b("مشكلة معيار ومعايرة","Criterion and calibration problem"),b("تحيز تفضيل شخصي محتمل","Instructor-preference bias is possible"),b("سلوك موثق أو فيديو واتفاق على مرساة.","Recorded behaviour or video and an agreed anchor."),b("إعادة صياغة البند كسلوك ملاحظ ومعايرة على أمثلة.","Rewrite the item as observable behaviour and calibrate with examples."),"Need More Data"),
  C(11,"advanced","فشل جماعي","Group-wide failure","ثمانية من عشرة فشلوا بعد إضافة Timer وتعليمات صوتية وتغيير ترتيب وحمل بدني معًا.","Eight of ten failed after a timer, audio instruction, order change, and physical load were added together.",["أربعة متغيرات متزامنة","فشل 80%"],["Four variables added together","80% failed"],["المجموعة ضعيفة"],["The group is weak"],"Cognitive","Cognitive",b("تصميم المحطة يمنع التشخيص","Station design prevents diagnosis"),b("Brief أو معيار قد يكونان سببًا","Brief or criterion may contribute"),b("نتائج كل متغير منفردًا وBaseline.","Baseline and isolated-variable results."),b("إعادة تصميم المحطة وإضافة عامل واحد في كل مرة.","Redesign the station and add one factor at a time."),"Need More Data"),
  C(12,"advanced","استعادة بعد الخطأ","Recovery after error","بعد خطأ غير حرج، استعجل المتدرب في المحاولة التالية وارتفع الخطأ، ثم عاد للـBaseline بعد Reset محدد.","After a non-critical error, the learner rushed the next trial and errors increased, then returned to baseline after a defined reset.",["سلسلة أخطاء بعد الحدث","تحسن بعد Reset"],["Error cascade after event","Improved after reset"],["انفعالي"],["Emotionally unstable"],"Affective","Cognitive",b("ERSI/Reset قابل للتدريب","ERSI/reset process is trainable"),b("تعب أو رغبة في تعويض الزمن","Fatigue or time-compensation strategy"),b("تكرار النمط مع حمل مضبوط.","Pattern replication under controlled load."),b("Reset مبكر، AAR غير عقابي، وتصعيد ضغط تدريجي.","Earlier reset, non-punitive AAR, and progressive pressure."),"Need More Data"),
  C(13,"advanced","نتيجة سريعة غير دقيقة","Fast but inaccurate response","زمن الاستجابة تحسن، لكن دقة الاختيار انخفضت وتباينت الحركة.","Response time improved, but choice accuracy fell and movement became inconsistent.",["الزمن أسرع","الدقة والاتساق أسوأ"],["Faster time","Worse accuracy and consistency"],["RSVMI ممتاز"],["Excellent RSVMI"],"Psychomotor","Cognitive",b("السرعة سبقت التكامل","Speed outpaced integration"),b("DMUS أو مهارة فنية غير ثابتة","DMUS or unstable technical skill"),b("محاولات بدقة أولًا وإشارات متوازنة.","Accuracy-first trials with balanced cues."),b("إعادة معيار الدقة، ثم سرعة تدريجية دون خفضه.","Restore accuracy criterion, then add speed without lowering it."),"No-Go"),
  C(14,"advanced","نمط مرتبط بالنوم","Sleep-linked pattern","انخفض الأداء في صباح واحد بعد نوم قصير حسب إفادة المتدرب.","Performance declined on one morning after self-reported short sleep.",["إفادة نوم قصيرة","جلسة واحدة منخفضة"],["Short-sleep report","One low session"],["SCR مثبت"],["SCR is proven"],"Cognitive","Cognitive",b("لا يوجد تشخيص مدعوم","No supported diagnosis"),b("توقيت، تعب، مرض، أو اختلاف مهمة","Timing, fatigue, illness, or task difference"),b("سجل طولي للنوم والتوقيت والأداء.","Longitudinal sleep, timing, and performance record."),b("جمع بيانات فقط وإدارة الجدول؛ لا حرمان متعمد.","Collect data and manage scheduling; no deliberate deprivation."),"Need More Data"),
  C(15,"advanced","الدرجة تعوّض الفشل","Score compensates for failure","النموذج يعطي 92% لأن نقاط السرعة والدقة عوضت بند أمان حرجًا.","The rubric gives 92% because speed and accuracy points compensated for a critical safety item.",["Critical Failure حدث","المعادلة أعطت نجاحًا"],["Critical Failure occurred","Formula returned pass"],["الأداء الكلي مقبول"],["Overall performance is acceptable"],"Affective","Technical",b("منطق التقييم غير صالح","Assessment logic is invalid"),b("Checklist لا يطبق Gate","Checklist does not enforce the gate"),b("لا بيانات إضافية مطلوبة للقرار.","No additional data is needed for the decision."),b("تطبيق Gate غير قابل للتعويض وإعادة تصميم الحساب.","Apply a non-compensable gate and redesign the scoring logic."),"No-Go"),
];

export const references = [
  {citation:"Bloom, B. S. et al. (1956). Taxonomy of Educational Objectives: Handbook I—Cognitive Domain.",supports:b("أساس المجال المعرفي وتدرج أهداف التفكير.","Foundation for the cognitive domain and progression of thinking objectives."),not:b("لا يثبت وحده فاعلية تدخل تدريبي ميداني بعينه.","Does not alone prove the effectiveness of a specific field intervention."),used:b("Learning Domains وObjective Builder.","Learning Domains and Objective Builder."),url:"https://archive.org/details/taxonomyofeducat0000bloo"},
  {citation:"Anderson, L. W., & Krathwohl, D. R. (Eds.). (2001). A Taxonomy for Learning, Teaching, and Assessing.",supports:b("الصياغة المعدلة: Remember إلى Create.","Revised progression from Remember to Create."),not:b("ليست نموذج تشخيص أداء فعلي.","Not a model for diagnosing actual performance."),used:b("المستويات المعرفية والأهداف.","Cognitive levels and objectives."),url:"https://www.worldcat.org/title/45008634"},
  {citation:"Krathwohl, D. R., Bloom, B. S., & Masia, B. B. (1964). Handbook II—Affective Domain.",supports:b("تدرج الانتباه والاستجابة والتقدير والتنظيم والالتزام.","Progression from receiving to internalization."),not:b("لا يبرر تشخيص الشخصية من ملاحظة قصيرة.","Does not justify personality diagnosis from brief observation."),used:b("Affective Domain وPerformance Profile.","Affective Domain and Performance Profile."),url:"https://www.worldcat.org/title/710720"},
  {citation:"Dave, R. H. (1970). Psychomotor Levels. In Developing and Writing Behavioral Objectives.",supports:b("المستويات الخمسة لتطور المهارة الحركية.","Five psychomotor skill-development levels."),not:b("لا يحدد جرعات ممارسة موحدة لكل المهارات.","Does not prescribe one practice dose for every skill."),used:b("Psychomotor ladder وStation Builder.","Psychomotor ladder and Station Builder."),url:"https://www.worldcat.org/title/310688"},
  {citation:"Fitts, P. M., & Posner, M. I. (1967). Human Performance.",supports:b("انتقال المهارة من التحكم الواعي إلى الثبات النسبي.","Skill progression from conscious control toward relative automaticity."),not:b("لا يجعل المحاولة الناجحة الواحدة دليل ثبات.","Does not make one successful attempt proof of stability."),used:b("رسائل الثبات وتصميم التكرار.","Stability guidance and practice design."),url:"https://www.worldcat.org/title/514326"},
  {citation:"Endsley, M. R. (1995). Toward a Theory of Situation Awareness in Dynamic Systems. Human Factors, 37(1), 32–64.",supports:b("الإدراك والفهم والتوقع داخل بيئات متغيرة.","Situation awareness in dynamic decision environments."),not:b("لا يجعل النتيجة النهائية مقياسًا وحيدًا للـSA.","Does not make final outcome a sole measure of SA."),used:b("SA ومعمل الحالات.","SA and Case Lab."),url:"https://doi.org/10.1518/001872095779049543"},
  {citation:"Sweller, J. (1988). Cognitive Load During Problem Solving: Effects on Learning. Cognitive Science, 12(2), 257–285.",supports:b("محدودية موارد المعالجة وتأثير الحمل على التعلم.","Limits on processing resources and effects of load on learning."),not:b("لا يثبت أن كل خطأ تحت التعقيد سببه CLM.","Does not prove every complex-task error is CLM."),used:b("CLM وتحذيرات تصميم المحطة.","CLM and station-design warnings."),url:"https://doi.org/10.1207/s15516709cog1202_4"},
  {citation:"Arnsten, A. F. T. (2009). Stress signalling pathways that impair prefrontal cortex structure and function. Nature Reviews Neuroscience, 10, 410–422.",supports:b("قابلية وظائف الانتباه والذاكرة العاملة للتأثر بالضغط غير المسيطر عليه.","Sensitivity of prefrontal attention and working-memory functions to uncontrollable stress."),not:b("لا يتيح تشخيصًا عصبيًا ميدانيًا من السلوك وحده.","Does not enable field neurological diagnosis from behaviour alone."),used:b("حدود تفسير الأداء الذهني.","Limits on cognitive-performance interpretation."),url:"https://doi.org/10.1038/nrn2648"},
  {citation:"Van Dongen, H. P. A. et al. (2003). The cumulative cost of additional wakefulness. Sleep, 26(2), 117–126.",supports:b("التدهور التراكمي للأداء مع تقييد النوم.","Cumulative performance degradation with sleep restriction."),not:b("لا يثبت SCR من يوم واحد أو تقرير ذاتي واحد.","Does not prove SCR from one day or one self-report."),used:b("SCR وحدود الملف الشخصي.","SCR and profile limitations."),url:"https://doi.org/10.1093/sleep/26.2.117"},
  {citation:"Harden, R. M. et al. (1975). Assessment of clinical competence using objective structured examination. BMJ, 1, 447–451.",supports:b("المحطات المنظمة والـChecklist والمعايير المحددة مسبقًا.","Structured stations, checklists, and pre-defined criteria."),not:b("لا يجعل أي محطة تلقائيًا اختبارًا صالحًا أو مثبتًا علميًا.","Does not make any station automatically valid or scientifically validated."),used:b("Station Builder وCalibration Lab.","Station Builder and Calibration Lab."),url:"https://doi.org/10.1136/bmj.1.5955.447"},
  {citation:"Internal Course Reference (2026). قراءة الأداء الكامل في تدريب الرماية — Learning Domains + The Trifecta.",supports:b("التركيب التشغيلي، الأمثلة، الـGate، والفصل بين البناء والتشخيص.","Operational framing, examples, safety gate, and build-versus-diagnose distinction."),not:b("ليس دراسة تحقق مستقلة أو معيارًا سريريًا.","Not an independent validation study or clinical standard."),used:b("جميع وحدات التطبيق.","All application modules."),url:"#source-note"},
  {citation:"Internal Course Reference (2026). العمود الذهني والعصبي في الـTrifecta.",supports:b("العائلات العشر، الأسئلة العملية، المؤشرات، والمقاييس المقترحة.","Ten families, practical questions, indicators, and proposed metrics."),not:b("لا يجيز تشخيصًا عصبيًا أو سريريًا.","Does not authorize neurological or clinical diagnosis."),used:b("Cognitive / Neurophysiological Explorer.","Cognitive / Neurophysiological Explorer."),url:"#source-note"},
];

export const knowledgeChecks = [
  {q:b("متدرب شرح القاعدة ثم خالفها تحت Timer. أي عبارة أدق؟","A learner explained the rule then broke it under a timer. Which statement is strongest?"), options:[b("المعرفة غير موجودة","Knowledge is absent"),b("الدليل يثبت مشكلة شخصية","Evidence proves a personality issue"),b("المعرفة موجودة؛ سبب الانهيار يحتاج بيانات","Knowledge exists; the breakdown needs more evidence")], answer:2, why:b("الشرح يثبت مستوى معرفيًا، لكنه لا يثبت الثبات الحركي أو السلوكي تحت الحمل.","Explanation supports a cognitive level but not motor or behavioural stability under load.")},
  {q:b("هل يمكن أن تعوّض السرعة Critical Safety Failure؟","Can speed compensate for a Critical Safety Failure?"),options:[b("نعم إذا تجاوز المجموع 90%","Yes above 90%"),b("لا؛ هو Gate غير قابل للتعويض","No; it is a non-compensable gate"),b("حسب رأي المقيم","At assessor discretion")],answer:1,why:b("المصدر الداخلي يحدد السلامة الحرجة كشرط نجاح مستقل.","The internal source defines critical safety as an independent pass gate.")},
  {q:b("ثمانية من عشرة فشلوا بعد إضافة أربعة متغيرات. أول تدخل؟","Eight of ten fail after four variables are added. First intervention?"),options:[b("إعادة التدريب نفسه","Repeat the same training"),b("اختبار الشخصية","Assess personality"),b("العودة للـBaseline وعزل المتغيرات","Return to baseline and isolate variables")],answer:2,why:b("المحطة الحالية لا تسمح بتحديد أول سبب للانهيار.","The current station cannot identify the first breakdown cause.")},
  {q:b("زمن رد فعل سريع وحده يثبت RSVMI.","Fast reaction time alone proves RSVMI."),options:[b("صحيح","True"),b("خطأ","False")],answer:1,why:b("يلزم الجمع بين الزمن ودقة الاختيار والتوافق الحركي عبر محاولات.","Time must be combined with choice accuracy and motor coordination across trials.")},
  {q:b("أي صياغة أكثر ملاحظة؟","Which wording is most observable?"),options:[b("يفهم الأمان","Understands safety"),b("يكون منضبطًا","Is disciplined"),b("يطبق قرار الإيقاف خلال ثانيتين من Cue المحدد","Applies the stop decision within two seconds of the defined cue")],answer:2,why:b("تحدد سلوكًا وشرطًا ومعيارًا يمكن تسجيله.","It specifies a recordable behaviour, condition, and criterion.")},
];
